spring.application.name: Rbn-Eureka-Server
server:
  port: 8761
eureka:
#  server:
#     enableSelfPreservation: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    