server.port: 8080
management.endpoints.web.exposure.include: "*"
spring.application.name: zuul-server

eureka.client:
   serviceUrl.defaultZone: http://localhost:8761/eureka
#   instance.preferIpAddress: true
   fetchRegistry: true
   registerWithEureka: true

zuul:
   prefix: /api
   routes:
      client1-any:
         path: /client1/any
         serviceId: client1
         stripPrefix: true
#      client1-my-value:
#         path: /client1/my-value
#         serviceId: client1
#         stripPrefix: true
#      product-by-id:
#         path: /product/*
#         serviceId: client-product
#         stripPrefix: true
#      customer-by-id:
#         path: /product/*
#         serviceId: client-customer
#         stripPrefix: true